# Generated by Django 5.2.4 on 2025-07-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='telefono',
            new_name='telefono_emergencia',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='participacion',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='alumno',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ci',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='año_academico',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='curso',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='seccion',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maestro',
            name='años_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maestro',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maestro',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestro',
            name='grado_academico',
            field=models.CharField(blank=True, choices=[('Bachiller', 'Bachiller'), ('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=50),
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='horas_semanales',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='materia',
            name='maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maestro'),
        ),
        migrations.AddField(
            model_name='padre',
            name='ci',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='padre',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participacion',
            name='tipo_participacion',
            field=models.CharField(choices=[('oral', 'Participación Oral'), ('escrita', 'Participación Escrita'), ('grupal', 'Trabajo Grupal'), ('individual', 'Trabajo Individual'), ('proyecto', 'Proyecto')], default='oral', max_length=50),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='token_qr',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
